# urls to google sheets

# tier classifications
known_url = "omicsynth/Known_gene_hits_sig.csv"
novel_url = "omicsynth/Novel_gene_hits_sig.csv"
difficult_url = "omicsynth/Difficult_gene_hits_sig.csv"

# SMR associations - differing significance thresholds
adjusted_sig = "omicsynth/NDD_sig_allcol.csv"
simple_sig = "omicsynth/sig_associations_05.csv"
all_associations = "omicsynth/NDD_SMR_genes_all.parquet"

#single cell coloc
coloc_url = "omicsynth/coloc_hits.csv"

# drug data
drug_db = 'omicsynth/drug_genome_dgidb.csv'

[gcp_service_account]
type = "service_account"
project_id = "tactile-welder-340020"
private_key_id = "e2cbc66c1f70c2bd73fcd27a8d1a2c58a479e372"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2GLre4PXt+e5f\nWTi9SHXne+Ipg/xere8Mqi6nGlQF6YQcCie+ETCD3bdAHzhm3vSgzbVCQr8a2fNh\n0HsUcyBo99hnoOmmVgacI0o4C+4o7iRYTSdPz6MQwW+y9kh0ghJ3roZO4PGD9UXO\nrZ04CVyWE0tVcCn7cc+W1hhwykAki7Mixa4r9yVyUhc6Z1DLQNGDFD9nHtqaM6Jv\nU7Qoh3D7wpMS91tk7+BBi03Rc46GLShJX30QciL3AI+628G/PKrz4pq44+WApwYM\nb6twonBTAJalNGQksEcMy7ig6z1pCI2dSqLuhqALeOF7bH3LXNMOfAmAI9jlgmOC\nwZ+RQjufAgMBAAECggEAP5GRhuX0pI+YEgwlHRrzIgzizohnbSv+JCcy4x3zUB8N\ngfZfmmAI1jfr1YQwneTedFZrnQaNDVQhvTdZCDIKkepXzxFjD7C/XPmK2tb7XKmJ\n4ZOJkjiTnfFRS6HjeFzCEqrH8zhex6izpmuAU4QdILz6kwh1d3RrOiZiYNmSG89b\n7RdfX79d+9o9JQCC8xYpZsaf6Div5N5SFHyNBaVbYMAjouimUEQXiZTXizAvZ3oC\nRP1i6RtEn3S0FEk514zD7fx/PvNkGOiO2vFPwLFTVAFOp6Nrq5fthimFeY5jkT9u\np7fcI2HVeIt3lb21ci/Q/hFavP6Wi5BAVGqT4BEA7QKBgQDnbo4B2do2mehU0Zn9\n1po/LNC88bG7eA4ibiY2WOgYBIwlkG1zOyJxydHGYuE7BiQojAFfIKmeFbVYkpaV\ng24ohyECHGuxOJQCEPcmtM7tjHZtr4Glb9UIbY8hw+oryfBS4CLd+vUa+o0YXaAD\noy5gzl0c31ZxDjVCnTp7NIIvGwKBgQDJbW3XlARJEd5zGc1XZCc6qXgIAfRm5C0n\nfHwqQDrTc2koJqcNnCv/Hlrs9b0dLE9zgbsxVAXXPmjYUJl5L8bW2kwO/dhT1Sw2\nIkNX9Wxr3HsaSQgRPvk1eqnDoE7aAJbSzZkktuYnT20w9WmSGSDpGI5oblKbA8Pl\nQSNCymi5zQKBgQCZ8M7i6k8dLKj+6mEdGMeHKD88vyQzB/uW6V/fnKndeADk57n2\nASq7N7yi0pjw0vfwRJiQ9z/8GIKFBRTHJSJ8MM5DAjacLn89FJ3hkDloh5srAKgj\nLE0vCvk/Q3sbX3rNFav7rfel121M/NH4OW4bFImZL/Hmx8WjpsQEufuyawKBgBeW\nzCVR/Up9YDrEi8qvPPTeweLWL8QY9rzIFFZyXTFEM81y8V9jqbdf27Aiezo+ZTOW\nvtBhEaoKcgbbMY4CrVueBwg+bCYtMddJHe/gGwlqsbP7V4mFgXPk4Jq7XGClbwRS\n9ZtaHAwAfj4cj3d/n94MdSj/uobS4w8nGLUKtUcFAoGAPVZIKExP2m4qbvAWPzXN\ns9fra9sI7vUs1OhFMrIvZSNGtiDIHvIt+f8qqt7xXc48rx7WzQ3TtI53TQPmQHxu\nAuXzbVCvSfwFrNBhs4QFy7HrYy8XOYSS7NFKC3ShbmZ1lov5lF8YdhGdHYkA0Qs4\nhXPPKXcUB9bkKCgV/9ymPxk=\n-----END PRIVATE KEY-----\n"
client_email = "os-streamlit@tactile-welder-340020.iam.gserviceaccount.com"
client_id = "105040615421324226564"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/os-streamlit%40tactile-welder-340020.iam.gserviceaccount.com"
universe_domain = "googleapis.com"